name: Deploy to Akamai ION

on:
  repository_dispatch:
    types: [akamai-deploy-workflow]

jobs:  
  build-docker-image:
    runs-on: ubuntu-latest

    env: 
      PIPELINE_REPO: ${{ github.event.client_payload.repository }}
      AKAMAI_NETWORK: ${{ github.event.client_payload.akamai_network }}
      ENVIRONMENT: ${{ github.event.client_payload.environment }}
      PIPELINE_NAME: ${{ github.event.client_payload.pipeline_name }}
      PROPERTY_NAME: ${{ github.event.client_payload.property_name }}      
   
    steps:
      - name: Checkout CDN-akamai repository
        uses: actions/checkout@v4
        with:
          path: CDN-akamai

      - name: Checkout  ${{ github.event.client_payload.repository }} repository
        uses: actions/checkout@v4
        with:
          repository: tvamsi66/devops1
          path: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS1 }}

      - name: ls CDN-akamai repository
        run: ls -R CDN-akamai

      - name: ls ${{ github.event.client_payload.repository }} repository
        run: ls -R ${{ github.event.client_payload.repository }}

      - name: Create .edgerc file
        env: 
          AKAMAI_CLIENT_SECRET: ${{ secrets.AKAMAI_CLIENT_SECRET }}
          AKAMAI_HOST: ${{ secrets.AKAMAI_HOST }}
          AKAMAI_ACCESS_TOKEN: ${{ secrets.AKAMAI_ACCESS_TOKEN }}
          AKAMAI_CLIENT_TOKEN: ${{ secrets.AKAMAI_CLIENT_TOKEN }}
        run: |
          echo "[papi]" > edgerc.config
          echo "client_secret = ${AKAMAI_CLIENT_SECRET}" >> edgerc.config
          echo "host = ${AKAMAI_HOST}" >> edgerc.config
          echo "access_token = ${AKAMAI_ACCESS_TOKEN}" >> edgerc.config
          echo "client_token = ${AKAMAI_CLIENT_TOKEN}" >> edgerc.config
          ls -las
          cat edgerc.config

      - name: Build Docker image
        run: docker build --build-arg PIPELINE_REPO="${{ env.PIPELINE_REPO }}" -t my-docker-image -f CDN-akamai/Dockerfile .

      - name: Instantiate Docker Container and Deploy pipeline
        run: docker run --name my-container -e AKAMAI_NETWORK="$AKAMAI_NETWORK" -e ENVIRONMENT="$ENVIRONMENT" -e PIPELINE_NAME="$PIPELINE_NAME" -e PROPERTY_NAME="$PROPERTY_NAME" my-docker-image
        
      # Add more steps as needed for additional testing or validation

      - name: Clean up Docker container
        run: docker rm my-container

      - name: Clean up Docker images
        run: docker rmi my-docker-image
