name: Deploy to Akamai ION

on:
  repository_dispatch:
    types: [akamai-deploy-workflow]

jobs:  
  build-docker-image:
    runs-on: ubuntu-latest

    env: 
      REPO: ${{ github.event.client_payload.repository }}
   
    steps:
      - name: Checkout CDN-akamai repository
        uses: actions/checkout@v4
        with:
          path: CDN-akamai

      - name: Checkout  ${{ github.event.client_payload.repository }} repository
        uses: actions/checkout@v4
        with:
          repository: tvamsi66/devops1
          path: ${{ github.event.client_payload.repository }}
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS1 }}

      - name: ls CDN-akamai repository
        run: ls -R CDN-akamai

      - name: ls ${{ github.event.client_payload.repository }} repository
        run: ls -R ${{ github.event.client_payload.repository }}

      - name: Create .edgerc file
        env: 
          AKAMAI_CLIENT_SECRET: ${{ secrets.AKAMAI_CLIENT_SECRET }}
          AKAMAI_HOST: ${{ secrets.AKAMAI_HOST }}
          AKAMAI_ACCESS_TOKEN: ${{ secrets.AKAMAI_ACCESS_TOKEN }}
          AKAMAI_CLIENT_TOKEN: ${{ secrets.AKAMAI_CLIENT_TOKEN }}
        run: |
          echo "[papi]" > edgerc.config
          echo "client_secret = ${AKAMAI_CLIENT_SECRET}" >> edgerc.config
          echo "host = ${AKAMAI_HOST}" >> edgerc.config
          echo "access_token = ${AKAMAI_ACCESS_TOKEN}" >> edgerc.config
          echo "client_token = ${AKAMAI_CLIENT_TOKEN}" >> edgerc.config
          ls -las
          cat edgerc.config

      - name: Build Docker image
        run: docker build --build-arg REPO="${{ env.REPO }}" -t my-docker-image -f CDN-akamai/Dockerfile .

      - name: Run tests
        #run: docker run -i --name my-container my-docker-image
        run: docker run --name my-container -e AKAMAI_NETWORK="${{ github.event.client_payload.akamai_network }}" -e ENVIRONMENT="${{ github.event.client_payload.environment }}" -e PIPELINE_NAME="${{ github.event.client_payload.pipeline_name }}" -e PROPERTY_NAME="${{ github.event.client_payload.property_name }}" my-docker-image
        
      # Add more steps as needed for additional testing or validation

      - name: Clean up Docker container
        run: docker rm my-container

      - name: Clean up Docker images
        run: docker rmi my-docker-image
