name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-docker-image -f Dockerfile .

      - name: Run Docker container
        run: docker run -d --name my-container my-docker-image

      - name: Test Docker container
        run: |
          docker exec my-container echo "Running tests..."
          
      # Add more steps as needed for additional testing or validation

      - name: Stop and remove Docker container
        run: docker stop my-container && docker rm my-container

      - name: Clean up Docker images
        run: docker rmi my-docker-image
