name: Deploy Pipeline to Akamai ION

on:
  workflow_dispatch:
    inputs:
      akamai_network:
        description: "Akamai Network"
        default: "tst1"

jobs:
    
  hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.akamai_network }}"
  
  build-docker-image:
    runs-on: ubuntu-latest
   
    steps:
      
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout secondary repository
        uses: actions/checkout@v4
        with:
          repository: tvamsi66/devops1
          path: devops1
          token: ${{ secrets.SECRET_ACCESS_TOKEN_DEVOPS1 }}

      - name: ls main repository
        run: ls -R main

      - name: ls secondary repository
        run: ls -R devops1

      - name: Build Docker image
        run: docker build -t my-docker-image -f main/Dockerfile .

      - name: Run tests
        #run: docker run -i --name my-container my-docker-image
        run: docker run --name my-container -e USER_INPUT="${{ github.event.inputs.akamai_network }}" my-docker-image
        
      # Add more steps as needed for additional testing or validation

      - name: Clean up Docker container
        run: docker rm my-container

      - name: Clean up Docker images
        run: docker rmi my-docker-image
