name: Docker Build and Test 1

on:
  workflow_dispatch:
    inputs:
      akamai_network:
        description: "Akamai Network"
        default: "tst1"

jobs:
    
  hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.akamai_network }}"
  
  build-and-test:
    runs-on: ubuntu-latest
   
    steps:
      
      - name: Checkout repository1
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: tvamsi66/devops1
          path: devops1

      - name: list directory
        run: ls -R /

      - name: Build Docker image
        run: docker build -t my-docker-image -f Dockerfile .

      - name: Run tests
        #run: docker run -i --name my-container my-docker-image
        run: docker run --name my-container -e USER_INPUT="${{ github.event.inputs.akamai_network }}" my-docker-image
        
      # Add more steps as needed for additional testing or validation

      - name: Clean up Docker container
        run: docker rm my-container

      - name: Clean up Docker images
        run: docker rmi my-docker-image
