name: Private Workflow

on:
  workflow_dispatch:
    inputs:
      akamai_network:
        description: "Akamai Network"
        default: "tst1"
        
  repository_dispatch:
    types: [trigger-devops-private-workflow]
    
jobs:
 
  test-runs:
    runs-on: ubuntu-latest
   
    steps:
      
      - name: Checkout main repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout secondary repository
        uses: actions/checkout@v4
        with:
          repository: tvamsi66/devops1
          path: devops1
          token: ${{ secrets.ACCESS_TOKEN_DEVOPS1 }}

      - name: ls main repository
        run: ls -R main

      - name: ls secondary repository
        run: ls -R devops1

      - name: Print received data
        run: echo "Received data:${{ github.event.client_payload.data }}"
